spring:
  application:
    name: mailsender

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        from:
          email: noreply@securehub.com
          name: SecureHub
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  from:
    email: noreply@securehub.com
    name: SecureHub

kafka:
  consumer:
    bootstrap-servers: localhost:29092
    group-id: mail-sender-group
    auto-offset-reset: earliest

logging:
  level:
    root: INFO
    com.securehub.mailsender: DEBUG