spring:
  application:
    name: mailsender

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: mail-sender-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
