spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

api:
  jwt:
    secret: jwt-secret
    expirationInSeconds: 10
  encrypt:
    secret: encrypt-secret

logging:
  level:
    root: INFO
    com.securehub.auth: DEBUG