spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  secret: secret
  expirationInSeconds: 3600

logging:
  level:
    root: INFO
    com.securehub.auth: DEBUG